'use strict';

const ACHIEVEMENTS = [
    // BEGINNER
    { id:'welcome', name:'Welcome', category:'beginner', ap:10, image:'welcome_first_round_played.png', description:'Complete your first UNO round.', triggerTypes:['round_end'], stat:null, threshold:null },
    { id:'good_start', name:'A Good Start', category:'beginner', ap:30, image:'good_start_first_win.png', description:'Win your first UNO match.', triggerTypes:['series_end'], stat:null, threshold:null },
    { id:'the_last_one', name:'The Last One', category:'beginner', ap:10, image:'the_last_one_first_uno_call.png', description:'Call UNO for the first time.', triggerTypes:['uno_called'], stat:null, threshold:null },
    { id:'joker', name:'Joker', category:'beginner', ap:30, image:'joker_wild_draw_four_hit.png', description:'Make an opponent draw cards with Wild Draw Four.', triggerTypes:['card_placed'], stat:null, threshold:null },
    { id:'our_house', name:'Our House', category:'beginner', ap:50, image:'our_house_5_wins_nonstandard.png', description:'Complete 5 matches with non-original ruleset.', triggerTypes:['series_end'], stat:null, threshold:5 },
    { id:'good_eye', name:'Good Eye', category:'beginner', ap:50, image:'good_eye_see_15_missed_uno.png', description:'Observe 15 missed UNO calls.', triggerTypes:['uno_missed_seen'], stat:null, threshold:15 },
    { id:'wow_signal', name:'WOW Signal!', category:'beginner', ap:10, image:'wow_signal_open_chat.png', description:'Open the chat panel for the first time.', triggerTypes:['chat_opened'], stat:null, threshold:null },
    { id:'ping', name:'Ping!', category:'beginner', ap:5, image:'ping_send_chat.png', description:'Send a chat notification.', triggerTypes:['chat_sent'], stat:null, threshold:null },
    { id:'pong', name:'Pong!', category:'beginner', ap:5, image:'pong_receive_chat.png', description:'Receive a chat message.', triggerTypes:['chat_received'], stat:null, threshold:null },
    { id:'identity', name:'I Am Not The Same As You', category:'beginner', ap:10, image:'identity_upload_avatar.png', description:'Upload a custom avatar.', triggerTypes:['avatar_changed'], stat:null, threshold:null },
    { id:'identity_crisis', name:'Identity Crisis', category:'beginner', ap:10, image:'identity_crisis_change_name.png', description:'Change your display name.', triggerTypes:['name_changed'], stat:null, threshold:null },
    { id:'forget_it', name:'Forget It', category:'beginner', ap:30, image:'forget_it_first_plus8_penalty.png', description:'Receive your first +8 UNO penalty.', triggerTypes:['uno_missed_penalty'], stat:null, threshold:null },
    { id:'jukebox', name:'Jukebox', category:'beginner', ap:15, image:'jukebox_change_music.png', description:'Change the music track.', triggerTypes:['jukebox_changed'], stat:null, threshold:null },
    { id:'quitter', name:'Quitter', category:'beginner', ap:5, image:'quitter_leave_match.png', description:'Leave a match via the quit button.', triggerTypes:['quit'], stat:null, threshold:null },
    { id:'hoarder', name:'Hoarder', category:'beginner', ap:30, image:'greedy_have_20_cards_in_hand.png', description:'Have 25 or more cards in your hand at once.', triggerTypes:['hand_check'], stat:null, threshold:null },

    // ADVANCED
    { id:'right_choice', name:'The Right Choice', category:'advanced', ap:100, image:'right_choice_40_color_changes.png', description:'Change color with wild cards 40 times.', triggerTypes:['card_placed'], stat:'color_changes', threshold:40 },
    { id:'nerves_of_steel', name:'Nerves of Steel', category:'advanced', ap:100, image:'nerves_of_steel_20_wdf_wins.png', description:'Play Wild Draw Four 20 times.', triggerTypes:['round_end'], stat:'cards_plus4', threshold:20 },
    { id:'sam_the_swift', name:'Sam the Swift', category:'advanced', ap:75, image:'sam_the_swift_fast_match_win.png', description:'Win a full match in under 15 minutes.', triggerTypes:['series_end'], stat:null, threshold:null },
    { id:'quicksilver', name:'Quicksilver', category:'advanced', ap:50, image:'quicksilver_round_under_5min.png', description:'Win a round in under 5 minutes.', triggerTypes:['round_end'], stat:null, threshold:null },
    { id:'passive_aggressive', name:'Passive Aggressive', category:'advanced', ap:60, image:'passive_aggressive_no_punishment_round.png', description:'Win a round without playing any punishment cards.', triggerTypes:['round_end'], stat:null, threshold:null },
    { id:'colorblind', name:'Colorblind', category:'advanced', ap:60, image:'colorblind_no_color_change_round.png', description:'Complete a round without changing color.', triggerTypes:['round_end'], stat:null, threshold:null },
    { id:'hexa', name:'Hexa', category:'advanced', ap:40, image:'hexa_pickup_plus6_stacked.png', description:'Pick up exactly +6 stacked cards.', triggerTypes:['stack_taken'], stat:null, threshold:null },
    { id:'stacked', name:'Stacked', category:'advanced', ap:40, image:'stacked_pickup_plus8_stacked.png', description:'Pick up +8 stacked cards.', triggerTypes:['stack_taken'], stat:null, threshold:null },

    // ONLINE
    { id:'socializer', name:'Socializer', category:'online', ap:50, image:'socializer_10_online_wins.png', description:'Win 10 matches with at least one other human.', triggerTypes:['series_end'], stat:null, threshold:10 },
    { id:'only_human', name:'Only Human', category:'online', ap:80, image:'only_human_vs_4_humans.png', description:'Play a match against 4 other humans.', triggerTypes:['series_end'], stat:null, threshold:null },
    { id:'quadro', name:'Quadro', category:'online', ap:70, image:'quadro_vs_3_humans_no_ai.png', description:'Play a match against 3 humans, no AI.', triggerTypes:['series_end'], stat:null, threshold:null },
    { id:'trinity', name:'Trinity', category:'online', ap:60, image:'trinity_vs_2_humans_no_ai.png', description:'Play a match against 2 humans, no AI.', triggerTypes:['series_end'], stat:null, threshold:null },
    { id:'duel', name:'Duel', category:'online', ap:40, image:'duel_vs_1_human_no_ai.png', description:'Play a match against 1 human, no AI.', triggerTypes:['series_end'], stat:null, threshold:null },
    { id:'the_last_stand', name:'The Last Stand', category:'online', ap:100, image:'the_last_stand_win_vs_4_humans.png', description:'Win a match against 4 other humans.', triggerTypes:['series_end'], stat:null, threshold:null },
    { id:'housekeeper', name:'Housekeeper', category:'online', ap:10, image:'housekeeper_host_first_game.png', description:'Host a game for the first time.', triggerTypes:['game_created'], stat:null, threshold:null },
    { id:'be_my_guest', name:'Be My Guest!', category:'online', ap:10, image:'be_my_guest_join_multiplayer.png', description:'Join a multiplayer game (not AI only).', triggerTypes:['game_joined'], stat:null, threshold:null },
    { id:'pariah', name:'Pariah', category:'online', ap:10, image:'pariah_host_ai_only_4_bots.png', description:'Host a 4-AI-only game.', triggerTypes:['game_created'], stat:null, threshold:null },
    { id:'no_segregation', name:'No Segregation', category:'online', ap:50, image:'no_segregation_10_mixed_wins.png', description:'Win 10 matches with at least one human and one AI.', triggerTypes:['series_end'], stat:null, threshold:10 },

    // VS AI — Easy
    { id:'lets_play_alone', name:"Let's Play Alone!", category:'vs_ai', ap:50, image:'lets_play_alone_5_wins_1_easy_ai.png', description:'Win 5 matches vs 1 easy AI, no humans.', triggerTypes:['series_end'], stat:null, threshold:5 },
    { id:'i_want_more', name:'I Want More!', category:'vs_ai', ap:70, image:'i_want_more_5_wins_2_easy_ai.png', description:'Win 5 matches vs 2 easy AI, no humans.', triggerTypes:['series_end'], stat:null, threshold:5 },
    { id:'push_the_pedal', name:'Push the Pedal!', category:'vs_ai', ap:90, image:'push_the_pedal_5_wins_3_easy_ai.png', description:'Win 5 matches vs 3 easy AI, no humans.', triggerTypes:['series_end'], stat:null, threshold:5 },
    { id:'dont_mess_around', name:"Don't Mess Around", category:'vs_ai', ap:100, image:'dont_mess_around_5_wins_4_easy_ai.png', description:'Win 5 matches vs 4 easy AI, no humans.', triggerTypes:['series_end'], stat:null, threshold:5 },
    // Medium
    { id:'robotics', name:'Robotics', category:'vs_ai', ap:50, image:'robotics_5_wins_1_medium_ai.png', description:'Win 5 matches vs 1 medium AI, no humans.', triggerTypes:['series_end'], stat:null, threshold:5 },
    { id:'still_just_a_machine', name:'Still Just a Machine', category:'vs_ai', ap:70, image:'still_just_a_machine_5_wins_2_medium_ai.png', description:'Win 5 matches vs 2 medium AI, no humans.', triggerTypes:['series_end'], stat:null, threshold:5 },
    { id:'raise_stake', name:'Raise Stake', category:'vs_ai', ap:90, image:'raise_stake_5_wins_3_medium_ai.png', description:'Win 5 matches vs 3 medium AI, no humans.', triggerTypes:['series_end'], stat:null, threshold:5 },
    { id:'asimov', name:'ASIMOV', category:'vs_ai', ap:100, image:'asimov_5_wins_4_medium_ai.png', description:'Win 5 matches vs 4 medium AI, no humans.', triggerTypes:['series_end'], stat:null, threshold:5 },
    // Hard
    { id:'just_a_machine', name:'Just a Machine', category:'vs_ai', ap:50, image:'just_a_machine_5_wins_1_hard_ai.png', description:'Win 5 matches vs 1 hard AI, no humans.', triggerTypes:['series_end'], stat:null, threshold:5 },
    { id:'still_just_metal', name:'Still Just Metal', category:'vs_ai', ap:70, image:'still_just_metal_5_wins_2_hard_ai.png', description:'Win 5 matches vs 2 hard AI, no humans.', triggerTypes:['series_end'], stat:null, threshold:5 },
    { id:'machinehead', name:'Machinehead', category:'vs_ai', ap:90, image:'machinehead_5_wins_3_hard_ai.png', description:'Win 5 matches vs 3 hard AI, no humans.', triggerTypes:['series_end'], stat:null, threshold:5 },
    { id:'terminator', name:'Terminator', category:'vs_ai', ap:100, image:'terminator_5_wins_4_hard_ai.png', description:'Win 5 matches vs 4 hard AI, no humans.', triggerTypes:['series_end'], stat:null, threshold:5 },
    // Mixed
    { id:'the_horde', name:'The Horde', category:'vs_ai', ap:300, image:'the_horde_50_wins_3_ai_types.png', description:'Win 50 matches vs 3+ AI difficulty types, no humans.', triggerTypes:['series_end'], stat:null, threshold:50 },
    { id:'practice_makes_perfect', name:'Practice Makes Perfect', category:'vs_ai', ap:100, image:'practice_makes_perfect_100_ai_games.png', description:'Play 100 AI-only matches.', triggerTypes:['series_end'], stat:null, threshold:100 },

    // LONG-TERM
    { id:'be_heard', name:'Be Heard', category:'longterm', ap:50, image:'be_heard_20_uno_calls.png', description:'Call UNO successfully 20 times.', triggerTypes:['uno_called'], stat:'uno_calls_success', threshold:20 },
    { id:'shouting', name:'Shouting', category:'longterm', ap:360, image:'shouting_200_uno_calls.png', description:'Call UNO successfully 200 times.', triggerTypes:['uno_called'], stat:'uno_calls_success', threshold:200 },
    { id:'reflex', name:'Reflex', category:'longterm', ap:360, image:'reflex_500_uno_calls.png', description:'Call UNO successfully 500 times.', triggerTypes:['uno_called'], stat:'uno_calls_success', threshold:500 },
    { id:'warmup', name:'Warmup', category:'longterm', ap:100, image:'warmup_100_action_cards.png', description:'Play 100 action cards.', triggerTypes:['card_placed'], stat:'action_cards_played', threshold:100 },
    { id:'action_hero', name:'Action Hero', category:'longterm', ap:500, image:'action_hero_500_action_cards.png', description:'Play 500 action cards.', triggerTypes:['card_placed'], stat:'action_cards_played', threshold:500 },
    { id:'flying_higher', name:'Flying Higher', category:'longterm', ap:200, image:'flying_higher_50_wins_over_400pts.png', description:'Win 50 matches scoring 400+ points.', triggerTypes:['series_end'], stat:null, threshold:50 },
    { id:'high_stakes', name:'High Stakes', category:'longterm', ap:150, image:'high_stakes_50_wins_over_200pts.png', description:'Win 50 matches scoring 200+ points.', triggerTypes:['series_end'], stat:null, threshold:50 },
    { id:'the_highway', name:'The Highway', category:'longterm', ap:500, image:'the_highway_500_rounds_won.png', description:'Win 500 rounds.', triggerTypes:['round_end'], stat:'rounds_won', threshold:500 },
    { id:'dementia', name:'Dementia', category:'longterm', ap:200, image:'dementia_100_missed_uno_penalties.png', description:'Receive 100 missed-UNO +8 penalties.', triggerTypes:['uno_missed_penalty'], stat:'uno_missed_penalty', threshold:100 },
    { id:'determination', name:'Determination', category:'longterm', ap:1500, image:'determination_1000_long_matches.png', description:'Play 1000 matches with 5+ rounds.', triggerTypes:['series_end'], stat:null, threshold:1000 },
    { id:'grinding', name:'Grinding', category:'longterm', ap:500, image:'grinding_1000_rounds_played.png', description:'Play 1000 rounds.', triggerTypes:['round_end'], stat:'rounds_played', threshold:1000 },
    { id:'suffering', name:'Suffering', category:'longterm', ap:500, image:'suffering_500_plus4_punishments.png', description:'Receive +4 stacked punishment 500 times.', triggerTypes:['stack_taken'], stat:null, threshold:500 },
    { id:'deluge', name:'Deluge', category:'longterm', ap:1000, image:'deluge_5000_cards_played.png', description:'Play 5000 total cards.', triggerTypes:['round_end'], stat:null, threshold:5000 },
    { id:'something_good', name:'Something Good', category:'longterm', ap:100, image:'something_good_leaderboard_1st.png', description:'Reach #1 in any leaderboard category.', triggerTypes:['round_end'], stat:null, threshold:null },
    { id:'player', name:'Player', category:'longterm', ap:200, image:'player_2000_normal_cards.png', description:'Play 2000 cards of any type.', triggerTypes:['round_end'], stat:null, threshold:2000 },
    { id:'flux_capacitor', name:'Flux Capacitor', category:'longterm', ap:300, image:'flux_capacitor_45min_round.png', description:'Spend 240 minutes in-game total.', triggerTypes:['round_end'], stat:'played_time_seconds', threshold:14400 },
    { id:'great_scott', name:'Great Scott!', category:'longterm', ap:5000, image:'great_scott_120min_match.png', description:'Spend 240 hours in-game total.', triggerTypes:['round_end'], stat:'played_time_seconds', threshold:864000 },
    { id:'hardcore_master', name:'Hardcore Master', category:'longterm', ap:200, image:'Hardcore.png', description:'Win 50 matches in Hardcore mode.', triggerTypes:['series_end'], stat:null, threshold:50 },

    // LEVELS
    { id:'level_10',   name:'First Steps',      category:'longterm', ap:50,   image:'levelup_10.png',   description:'Reach level 10.',   triggerTypes:['round_end','series_end'], stat:'level', threshold:10   },
    { id:'level_50',   name:'Getting Serious',  category:'longterm', ap:100,  image:'levelup_50.png',   description:'Reach level 50.',   triggerTypes:['round_end','series_end'], stat:'level', threshold:50   },
    { id:'level_100',  name:'Centurion',        category:'longterm', ap:150,  image:'levelup_100.png',  description:'Reach level 100.',  triggerTypes:['round_end','series_end'], stat:'level', threshold:100  },
    { id:'level_150',  name:'Dedicated',        category:'longterm', ap:200,  image:'levelup_150.png',  description:'Reach level 150.',  triggerTypes:['round_end','series_end'], stat:'level', threshold:150  },
    { id:'level_250',  name:'Veteran',          category:'longterm', ap:300,  image:'levelup_250.png',  description:'Reach level 250.',  triggerTypes:['round_end','series_end'], stat:'level', threshold:250  },
    { id:'level_500',  name:'Elite',            category:'longterm', ap:500,  image:'levelup_500.png',  description:'Reach level 500.',  triggerTypes:['round_end','series_end'], stat:'level', threshold:500  },
    { id:'level_750',  name:'Master',           category:'longterm', ap:1000, image:'levelup_750.png',  description:'Reach level 750.',  triggerTypes:['round_end','series_end'], stat:'level', threshold:750  },
    { id:'level_1000', name:'Legend',           category:'longterm', ap:2000, image:'levelup_1000.png', description:'Reach level 1000.', triggerTypes:['round_end','series_end'], stat:'level', threshold:1000 },
];

const CHALLENGE_TEMPLATES = [
    { type:'punish_players',   label:'Punish players {x} times.',          minX:3,  maxX:15 },
    { type:'win_matches',      label:'Win {x} matches.',                   minX:1,  maxX:5  },
    { type:'win_rounds',       label:'Win {x} rounds.',                    minX:3,  maxX:12 },
    { type:'lose_matches',     label:'Lose {x} matches.',                  minX:1,  maxX:5  },
    { type:'lose_rounds',      label:'Lose {x} rounds.',                   minX:2,  maxX:8  },
    { type:'play_normal',      label:'Play {x} normal numbered cards.',    minX:10, maxX:50 },
    { type:'change_colors',    label:'Change color {x} times.',            minX:3,  maxX:15 },
    { type:'stack_plus2',      label:'Stack +2 cards {x} times.',          minX:2,  maxX:8  },
    { type:'stack_plus4',      label:'Stack +4 cards {x} times.',          minX:2,  maxX:6  },
    { type:'play_plus2',       label:'Play +2 cards {x} times.',           minX:3,  maxX:15 },
    { type:'skip_uno',         label:'Miss UNO press {x} times.',          minX:1,  maxX:5  },
    { type:'press_uno',        label:'Press UNO {x} times.',               minX:3,  maxX:12 },
    { type:'host_games',       label:'Host {x} games.',                    minX:1,  maxX:4  },
    { type:'join_games',       label:'Join {x} games.',                    minX:1,  maxX:4  },
    { type:'take_punishment',  label:'Receive punishment cards {x} times.',minX:3,  maxX:12 },
    { type:'play_plus4',       label:'Play +4 cards {x} times.',           minX:2,  maxX:8  },
    { type:'play_skip',        label:'Play Skip cards {x} times.',         minX:3,  maxX:12 },
    { type:'play_reverse',     label:'Play Reverse cards {x} times.',      minX:3,  maxX:12 },
    { type:'stack_punishment', label:'Participate in a stack {x} times.',  minX:2,  maxX:6  },
    { type:'play_red',         label:'Play {x} red cards.',                minX:5,  maxX:20 },
    { type:'play_green',       label:'Play {x} green cards.',              minX:5,  maxX:20 },
    { type:'play_blue',        label:'Play {x} blue cards.',               minX:5,  maxX:20 },
    { type:'play_yellow',      label:'Play {x} yellow cards.',             minX:5,  maxX:20 },
    { type:'play_0s',          label:'Play {x} zero cards.',               minX:2,  maxX:8  },
    { type:'play_1s',          label:'Play {x} one cards.',                minX:3,  maxX:12 },
    { type:'play_2s',          label:'Play {x} two cards.',                minX:3,  maxX:12 },
    { type:'play_3s',          label:'Play {x} three cards.',              minX:3,  maxX:12 },
    { type:'play_4s',          label:'Play {x} four cards.',               minX:3,  maxX:12 },
    { type:'play_5s',          label:'Play {x} five cards.',               minX:3,  maxX:12 },
    { type:'play_6s',          label:'Play {x} six cards.',                minX:3,  maxX:12 },
    { type:'play_7s',          label:'Play {x} seven cards.',              minX:3,  maxX:12 },
    { type:'play_8s',          label:'Play {x} eight cards.',              minX:3,  maxX:12 },
    { type:'play_9s',          label:'Play {x} nine cards.',               minX:2,  maxX:8  },
    { type:'win_ai_only',      label:'Win {x} AI-only matches.',           minX:1,  maxX:5  },
    { type:'play_action',      label:'Play {x} action cards.',             minX:5,  maxX:20 },
    { type:'press_uno_streak', label:'Press UNO {x} times in one game.',   minX:2,  maxX:8  },
    { type:'play_wild',        label:'Play {x} wild cards.',               minX:2,  maxX:10 },
    { type:'win_hardcore_games',  label:'Win {x} Hardcore matches.',  minX:10, maxX:15, weeklyMinX:30, weeklyMaxX:50 },
    { type:'play_hardcore_games', label:'Play {x} Hardcore matches.', minX:10, maxX:15, weeklyMinX:30, weeklyMaxX:50 },
];

module.exports = { ACHIEVEMENTS, CHALLENGE_TEMPLATES };
